source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "webrick"
gem "erb"
gem "base64"
gem "bigdecimal"
gem "kramdown-parser-gfm"
